### ISSUE TITLE
IndexError

### ISSUE THREAD

**Issue by kaci** [agobi/dijnet#1]
Üdv, egyrészt köszönet a kódért, de valami változhatott a díjnetnél, mert hibát dob nálam.

Környezet:
Archlinux, kernel: 4.14.5-1
Python 2.7.14
beautifulsoup4-4.6.0
certifi-2017.11.5
mechanicalsoup-0.9.0.post4
requests-2.18.4
urllib3-1.22

A hiba:
```
Traceback (most recent call last):
  File "dijnet.py", line 31, in <module>
    links = [t.td.a for t in page.select('table.szamla_table')[0].find_all('tr')]
IndexError: list index out of range
```
Szerintem a számlakeresés oldalon a keresés gomb nem működik valamiért a kódban, nem lép át az eredményoldalra. Próbálgattam, de nem sikerült megoldást találnom rá (nem ismertem eddig a mechanicalsoup-ot).
```
27 br.select_form(nr=0)
28 br.submit_selected()
29 page = br.get_current_page()
```
Üdv, kaci

**Comment by madeinjapan** [comment]
Üdv, megoldottam a problémát. Rá tudnál nézni?

Köszönöm! Üdv

**Comment by agobi** [comment]
Igen, változott a díjnet. Merge-eltem.
